ISPN-7714 Avoid usage of Class.getSimpleName() in favor of Class.getName()
* getSimpleName() requires access to all outer classes of the service class in question,
  which might not be available when the service is an inner class defined in an
  arquillian test suite and this may result in java.lang.NoClassDefFoundError