AsyncStore: don't return stale data (also fixes [ISPN-1174])
AsyncStore currently does not implement any of the load* methods. Reading
from the AsyncStore always returns data from the back-end store, without
checking enqueued changes first.

Thus, a cache using the AsyncStore may return stale data.

Example 1:
  ...config.eviction().maxEntries(1)...
  cache.put("X", "1");
  cache.put("Y", "1"); // force eviction of "X"
  Thread.sleep(1000); // wait for "X" to be stored
  cache.put("X", "2");
  cache.put("Y", "2"); // force eviction of "X"
  cache.get("X"); // may return "1" instead of "2"

Example 2:
  ...config.eviction().maxEntries(1)...
  cache.put("X", "1");
  cache.put("Y", "1"); // force eviction of "X"
  Thread.sleep(1000); // wait for "X" to be stored
  cache.remove("X");
  cache.get("X"); // may return "1" instead of null

This is also the root cause for entries disappearing from the cache for a
short time when they are evicted ([ISPN-1174]).

Implement all the load* methods to check the enqueued changes before
loading from the back-end store.

Unfortunately, this involves a complete redesign of the data structures, as
part of the enqueued state was held in linked lists (inefficient to access
by key) or even local variables.

Additionally, this patch fixes the following problems:
- AsyncStoreCoordinator prevents clean shutdown on VM exit (must be a
  daemon thread)
- AsycStore doesn't block if the configured modificationQueueSize is
  reached (causing OutOfMemoryError if data is added faster than can be
  handled by the back-end store)

Signed-off-by: Karsten Blees <blees@dcon.de>